#! /bin/sh
#  ---------------------------------------------------------------------------
#  Copyright (c) 2015 Quectel Wireless Solutions Co., Ltd. All Rights Reserved.
#  Quectel Wireless Solutions Proprietary and Confidential.
#  ---------------------------------------------------------------------------
#
# init.d script for quectel daemon

set -e

case "$1" in
       start)
                echo -n "Starting quectel_daemon: "
                start-stop-daemon -S -b -a /usr/bin/quectel_daemon
                echo "done"
                ;;
       stop)
                echo -n "Stopping quectel daemon: "
                start-stop-daemon -K -n quectel_daemon
                echo "done"
                ;;
       restart)
                $0 stop
                $0 start
                ;;
       *)
                echo "Usage: quectel_daemon { start | stop | restart }" >&2
                exit 1
                ;;
esac

exit 0
