#! /bin/sh
#  ---------------------------------------------------------------------------
#  Copyright (c) 2015 Quectel Wireless Solutions Co., Ltd. All Rights Reserved.
#  Quectel Wireless Solutions Proprietary and Confidential.
#  ---------------------------------------------------------------------------
#
# init.d script for quectel gps handle

set -e

case "$1" in
       start)
                echo -n "Starting quectel-smd-atcmd: "
                start-stop-daemon -S -b -a /usr/bin/quectel-smd-atcmd
                echo "done"
                ;;
       stop)
                echo -n "Stopping quectel smd atcmd: "
                start-stop-daemon -K -n quectel-smd-atcmd
                echo "done"
                ;;
       restart)
                $0 stop
                $0 start
                ;;
       *)
                echo "Usage: quectel-smd-atcmd { start | stop | restart }" >&2
                exit 1
                ;;
esac

exit 0
