#! /bin/sh

set -e

case "$1" in
start)
    # add by quectel 2016.06.26  end	
    echo -n "Starting quectel-tts-service "
    start-stop-daemon -S -b -a /usr/bin/quectel_tts_service
    echo "done"
    ;;
  stop)
    echo -n "Stopping atreset: "
    start-stop-daemon -K -n quectel_tts_service
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage quectel_tts_service{ start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
