#! /bin/sh
#
#Copyright (c) 2013 Qualcomm Technologies, Inc.  All Rights Reserved.
#Qualcomm Technologies Proprietary and Confidential.

# MCM_MOBILEAP_ConnectionManager   init.d script to start the Data Software's MCM_MOBILEAP_ConnectionManager daemon

set -e

case "$1" in
  start)
        echo -n "Starting MCM_MOBILEAP_ConnectionManager: "
        start-stop-daemon -S -b -a MCM_MOBILEAP_ConnectionManager /etc/mobileap_cfg.xml d
        echo "done"
        ;;
  stop)
        echo -n "Stopping QCMAP_ConnectionManager: "
        start-stop-daemon -K -n MCM_MOBILEAP_ConnectionManager
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage MCM_MOBILEAP_ConnectionManager { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
