#
# Makefile for quectel low_power_consume_driver_v2 drivers,
# The driver will be compile to be a kmod, used to be instead
# of low_power_consume_driver.
# 2018/5/12 gale  
#
obj-$(CONFIG_LOW_POWER_CONSUME_V2)	+= low_power_consume_driver_v2.o
