/*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*
  Copyright (c) 2013-2014 Qualcomm Technologies, Inc.  All Rights Reserved.
  Qualcomm Technologies Proprietary and Confidential.
=============================================================================*/
/*=============================================================================*/
/* DO NOT EDIT THIS FILE IF YOU DO NOT HAVE ACCESS TO SOURCE FOR IZAT BINARIES.
   THIS PROXY ACTS AS A LINK TO IZAT BINARIES.
   EDITING AND RECOMPILING THIS FILE WITHOUT RECOMPILING IZAT BINARIES
   CAN CAUSE UNKNOWN BEHAVIOR*/
/*=============================================================================*/

#ifndef LOC_API_PROXY_H
#define LOC_API_PROXY_H

#include <LocApiV02.h>
#include <LBSProxyBase.h>
#include <LBSApiV02.h>
#include <platform_lib_log_util.h>

namespace lbs_core {

class LocApiProxyV02 : public LocApiProxyBase {
protected:
    LBSApiV02 *mLBSApi;
    IzatApiV02 *mIzatApi;
public:
    LocApiProxyV02(LBSApiV02* lbsApi);
    virtual ~LocApiProxyV02();
    virtual void *getSibling2() { return (void *)mIzatApi; }
    locClientHandleType getClientHandle() { return mLBSApi->clientHandle; }
    int eventCb(locClientHandleType client_handle,
                uint32_t loc_event_id,
                locClientEventIndUnionType loc_event_payload);
};
}; //namespace lbs_core

#endif //LOC_API_PROXY_H
